Config = {}

Config.Locale = GetConvar('esx:locale', 'en')

Config.Weapons = {
	WEAPON_KNIFE = { item = 'knife' },
	WEAPON_NIGHTSTICK = { item = 'nightstick' },
	WEAPON_HAMMER = { item = 'hammer' },
	WEAPON_BAT = { item = 'bat' },
	WEAPON_GOLFCLUB = { item = 'golfclub' },
	WEAPON_CROWBAR = { item = 'crowbar' },
	WEAPON_PISTOL = { item = 'pistol' },
	WEAPON_COMBATPISTOL = { item = 'combatpistol' },
	WEAPON_APPISTOL = { item = 'appistol' },
	WEAPON_PISTOL50 = { item = 'pistol50' },
	WEAPON_MICROSMG = { item = 'microsmg' },
	WEAPON_SMG = { item = 'smg' },
	WEAPON_ASSAULTSMG = { item = 'assaultsmg' },
	WEAPON_ASSAULTRIFLE = { item = 'assaultrifle' },
	WEAPON_CARBINERIFLE = { item = 'carbinerifle' },
	WEAPON_ADVANCEDRIFLE = { item = 'advancedrifle' },
	WEAPON_MG = { item = 'mg' },
	WEAPON_COMBATMG = { item = 'combatmg' },
	WEAPON_PUMPSHOTGUN = { item = 'pumpshotgun' },
	WEAPON_SAWNOFFSHOTGUN = { item = 'sawnoffshotgun' },
	WEAPON_ASSAULTSHOTGUN = { item = 'assaultshotgun' },
	WEAPON_BULLPUPSHOTGUN = { item = 'bullpupshotgun' },
	WEAPON_STUNGUN = { item = 'stungun' },
	WEAPON_SNIPERRIFLE = { item = 'sniperrifle' },
	WEAPON_HEAVYSNIPER = { item = 'heavysniper' },
	WEAPON_REMOTESNIPER = { item = 'remotesniper' },
	WEAPON_GRENADELAUNCHER = { item = 'grenadelauncher' },
	WEAPON_RPG = { item = 'rpg' },
	WEAPON_STINGER = { item = 'stinger' },
	WEAPON_MINIGUN = { item = 'minigun' },
	WEAPON_GRENADE = { item = 'grenade' },
	WEAPON_STICKYBOMB = { item = 'stickybomb' },
	WEAPON_SMOKEGRENADE = { item = 'smokegrenade' },
	WEAPON_BZGAS = { item = 'bzgas' },
	WEAPON_MOLOTOV = { item = 'molotov' },
	WEAPON_FIREEXTINGUISHER = { item = 'fireextinguisher' },
	WEAPON_PETROLCAN = { item = 'petrolcan' },
	WEAPON_DIGISCANNER = { item = 'digiscanner' },
	WEAPON_BALL = { item = 'ball' },
	WEAPON_SNSPISTOL = { item = 'snspistol' },
	WEAPON_BOTTLE = { item = 'bottle' },
	WEAPON_GUSENBERG = { item = 'gusenberg' },
	WEAPON_SPECIALCARBINE = { item = 'specialcarbine' },
	WEAPON_HEAVYPISTOL = { item = 'heavypistol' },
	WEAPON_BULLPUPRIFLE = { item = 'bullpuprifle' },
	WEAPON_DAGGER = { item = 'dagger' },
	WEAPON_VINTAGEPISTOL = { item = 'vintagepistol' },
	WEAPON_FIREWORK = { item = 'firework' },
	WEAPON_HEAVYSHOTGUN = { item = 'heavyshotgun' },
	WEAPON_MARKSMANRIFLE = { item = 'marksmanrifle' },
	WEAPON_HOMINGLAUNCHER = { item = 'hominglauncher' },
	WEAPON_PROXMINE = { item = 'proxmine' },
	WEAPON_SNOWBALL = { item = 'snowball' },
	WEAPON_FLAREGUN = { item = 'flaregun' },
	WEAPON_GARBAGEBAG = { item = 'garbagebag' },
	WEAPON_HANDCUFFS = { item = 'handcuffs' },
	WEAPON_COMBATPDW = { item = 'combatpdw' },
	WEAPON_MARKSMANPISTOL = { item = 'marksmanpistol' },
	WEAPON_KNUCKLE = { item = 'knuckle' },
	WEAPON_HATCHET = { item = 'hatchet' },
	WEAPON_RAILGUN = { item = 'railgun' },
	WEAPON_MACHETE = { item = 'machete' },
	WEAPON_MACHINEPISTOL = { item = 'machinepistol' },
	WEAPON_SWITCHBLADE = { item = 'switchblade' },
	WEAPON_REVOLVER = { item = 'revolver' },
	WEAPON_DBSHOTGUN = { item = 'dbshotgun' },
	WEAPON_COMPACTRIFLE = { item = 'compactrifle' },
	WEAPON_AUTOSHOTGUN = { item = 'autoshotgun' },
	WEAPON_BATTLEAXE = { item = 'battleaxe' },
	WEAPON_COMPACTLAUNCHER = { item = 'compactlauncher' },
	WEAPON_MINISMG = { item = 'minismg' },
	WEAPON_PIPEBOMB = { item = 'pipebomb' },
	WEAPON_POOLCUE = { item = 'poolcue' },
	WEAPON_WRENCH = { item = 'wrench' },
	WEAPON_FLASHLIGHT = { item = 'flashlight' },
	GADGET_NIGHTVISION = { item = 'nightvision' },
	GADGET_PARACHUTE = { item = 'parachute' },
	WEAPON_FLARE = { item = 'flare' },
	WEAPON_SNSPISTOL_MK2 = { item = 'snspistol_mk2' },
	WEAPON_REVOLVER_MK2 = { item = 'revolver_mk2' },
	WEAPON_DOUBLEACTION = { item = 'doubleaction' },
	WEAPON_SPECIALCARBINE_MK2 = { item = 'specialcarbine_mk2' },
	WEAPON_BULLPUPRIFLE_MK2 = { item = 'bullpuprifle_mk2' },
	WEAPON_PUMPSHOTGUN_MK2 = { item = 'pumpshotgun_mk2' },
	WEAPON_MARKSMANRIFLE_MK2 = { item = 'marksmanrifle_mk2' },
	WEAPON_ASSAULTRIFLE_MK2 = { item = 'assaultrifle_mk2' },
	WEAPON_CARBINERIFLE_MK2 = { item = 'carbinerifle_mk2' },
	WEAPON_COMBATMG_MK2 = { item = 'combatmg_mk2' },
	WEAPON_HEAVYSNIPER_MK2 = { item = 'heavysniper_mk2' },
	WEAPON_PISTOL_MK2 = { item = 'pistol_mk2' },
	WEAPON_SMG_MK2 = { item = 'smg_mk2' }
}

Config.AmmoTypes = {
	AMMO_PISTOL = { item = 'pistol_ammo' },
	AMMO_SMG = { item = 'smg_ammo' },
	AMMO_FIREWORK = { item = 'firework_ammo' },
	AMMO_RIFLE = { item = 'rifle_ammo' },
	AMMO_MG = { item = 'mg_ammo' },
	AMMO_SHOTGUN = { item = 'shotgun_ammo' },
	AMMO_STUNGUN = { item = 'stungun_ammo' },
	AMMO_SNIPER = { item = 'sniper_ammo' },
	AMMO_SNIPER_REMOTE = { item = 'sniper_remote_ammo' },
	AMMO_MINIGUN = { item = 'minigun_ammo' },
	AMMO_GRENADELAUNCHER = { item = 'grenadelauncher_ammo' },
	AMMO_GRENADELAUNCHER_SMOKE = { item = 'grenadelauncher_smoke_ammo' },
	AMMO_RPG = { item = 'rpg_ammo' },
	AMMO_STINGER = { item = 'stinger_ammo' },
	AMMO_BALL = { item = 'ball' },
	AMMO_STICKYBOMB = { item = 'stickybomb' },
	AMMO_SMOKEGRENADE = { item = 'smokegrenade' },
	AMMO_BZGAS = { item = 'gzgas_ammo' },
	AMMO_FLARE = { item = 'flare_ammo' },
	AMMO_MOLOTOV = { item = 'molotov' },
	AMMO_TANK = { item = 'tank_ammo' },
	AMMO_SPACE_ROCKET = { item = 'space_rocket_ammo' },
	AMMO_PLANE_ROCKET = { item = 'plane_rocket_ammo' },
	AMMO_PLAYER_LASER = { item = 'player_laser_ammo' },
	AMMO_ENEMY_LASER = { item = 'enemy_laser_ammo' },
	AMMO_BIRD_CRAP = { item = 'bird_crap_ammo' }
}

for weaponName, weaponData in pairs(Config.Weapons) do
	local weaponKey = tostring(weaponName):lower()
	local translateFunc = (TranslateCap and type(TranslateCap) == "function") and TranslateCap or _U
	weaponData.label = ESX.GetWeaponLabel(weaponKey) or translateFunc(weaponKey)
end
